//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unicodex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unicodex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;!DOCTYPE ldml SYSTEM &quot;ldml.dtd&quot;&gt;
        ///&lt;!-- Copyright Â© 1991-2016 Unicode, Inc.
        ///For terms of use, see http://www.unicode.org/copyright.html
        ///Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.
        ///CLDR data files are interpreted according to the LDML specification (http://unicode.org/reports/tr35/)
        ///
        ///DO NOT CHANGE MANUALLY! Generated by: GenerateOtherAnnotations
        ///--&gt;
        ///&lt;ldml&gt;
        ///	&lt;identity&gt;
        ///		&lt;version number=&quot;$Revision: 12999 $&quot;/&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string annotations_en {
            get {
                return ResourceManager.GetString("annotations_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blocks-9.0.0.txt
        ///# Date: 2016-02-05, 23:48:00 GMT [KW]
        ///# © 2016 Unicode®, Inc.
        ///# For terms of use, see http://www.unicode.org/terms_of_use.html
        ///#
        ///# Unicode Character Database
        ///# For documentation, see http://www.unicode.org/reports/tr44/
        ///#
        ///# Format:
        ///# Start Code..End Code; Block Name
        ///
        ///# ================================================
        ///
        ///# Note:   When comparing block names, casing, whitespace, hyphens,
        ///#         and underbars are ignored.
        ///#         For example, &quot;Latin Extended-A&quot; and &quot;latin extended a&quot; are  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Blocks {
            get {
                return ResourceManager.GetString("Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///Copyright © 2003-2016 Unicode, Inc. and others. All rights reserved. Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of the Unicode data files and any associated documentation (the &quot;Data Files&quot;) or Unicode software and any associated documentation (the &quot;Software&quot;) to deal in the Data Files or Software without restriction, including without limitation the rights to use, copy, modify, merge, publish [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ldml {
            get {
                return ResourceManager.GetString("ldml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000;&lt;control&gt;;Cc;0;BN;;;;;N;NULL;;;;
        ///0001;&lt;control&gt;;Cc;0;BN;;;;;N;START OF HEADING;;;;
        ///0002;&lt;control&gt;;Cc;0;BN;;;;;N;START OF TEXT;;;;
        ///0003;&lt;control&gt;;Cc;0;BN;;;;;N;END OF TEXT;;;;
        ///0004;&lt;control&gt;;Cc;0;BN;;;;;N;END OF TRANSMISSION;;;;
        ///0005;&lt;control&gt;;Cc;0;BN;;;;;N;ENQUIRY;;;;
        ///0006;&lt;control&gt;;Cc;0;BN;;;;;N;ACKNOWLEDGE;;;;
        ///0007;&lt;control&gt;;Cc;0;BN;;;;;N;BELL;;;;
        ///0008;&lt;control&gt;;Cc;0;BN;;;;;N;BACKSPACE;;;;
        ///0009;&lt;control&gt;;Cc;0;S;;;;;N;CHARACTER TABULATION;;;;
        ///000A;&lt;control&gt;;Cc;0;B;;;;;N;LINE FEED (LF);;;;
        ///000B;&lt;contro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnicodeData {
            get {
                return ResourceManager.GetString("UnicodeData", resourceCulture);
            }
        }
    }
}
